In [1]:
import pandas as pd
df = pd.read_csv("한국전력거래소_5분단위 전력수급현황_20230430.csv",encoding = 'cp949')
df.head()

,기준일시,공급능력(MW),현재수요(MW),최대예측수요(MW),공급예비력(MW),공급예비율(퍼센트),운영예비력(MW),운영예비율(퍼센트)
0,2022-04-01 00:00,82494.25,62453.29,70100,20040.96,32.08951,9257.45,14.82300
1,2022-04-01 00:05,83807.25,62329.25,70700,21477.99,34.45893,10889.28,17.47058
2,2022-04-01 00:10,83799.12,61830.96,70700,21968.15,35.52937,10865.86,17.57350
3,2022-04-01 00:15,83790.42,61648.72,70700,22141.69,35.91589,10864.26,17.62284
4,2022-04-01 00:20,83770.82,61382.62,70700,22388.19,36.47318,10451.95,17.02754

In [2]:
df['기준일시'] = pd.to_datetime(df['기준일시'])

In [3]:
df.set_index('기준일시', inplace=True)

In [4]:
range_of_values = df.loc['2023-03-13':'2023-03-19']
pd.DataFrame(range_of_values)

,공급능력(MW),현재수요(MW),최대예측수요(MW),공급예비력(MW),공급예비율(퍼센트),운영예비력(MW),운영예비율(퍼센트)
기준일시,,,,,,,
2023-03-13 00:00:00,84908.51,58782.03,72459,26126.48,44.44637,11493.20,19.55223
2023-03-13 00:05:00,85917.51,58954.44,72459,26963.07,45.73543,11608.36,19.69040
2023-03-13 00:10:00,86266.17,58710.58,72459,27555.59,46.93462,11721.43,19.96476
2023-03-13 00:15:00,86280.27,58298.44,72459,27981.82,47.99755,11486.17,19.70237
2023-03-13 00:20:00,86249.03,58263.70,72459,27985.33,48.03218,11020.61,18.91506
...,...,...,...,...,...,...,...
2023-03-19 23:35:00,83627.65,58627.16,60700,25000.48,42.64317,10477.01,17.87057
2023-03-19 23:40:00,83621.96,57941.24,60700,25680.72,44.32200,10712.65,18.48882
2023-03-19 23:45:00,83618.93,57726.21,60700,25892.72,44.85435,10759.25,18.63841
2023-03-19 23:50:00,83630.28,57755.40,60700,25874.87,44.80078,10628.66,18.40289
2023-03-19 23:55:00,83628.97,57323.79,60700,26305.18,45.88876,10859.84,18.94474